[package]
name = "coincrypto"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.8"
bitcoin = "0.32"
khodpay-bip32 = "0.2.0"
khodpay-bip39 = "0.2.0"
hex = "0.4.3"
itertools = "0.14.0"
